# curl -i -H "Content-Type: application/json" -d '{"content":"hello", "important":false}' localhost:3000/api/notes
POST http://localhost:3000/api/notes HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI1ZWM2OWZiMjMxYzJlZGQzMTA1NmJhMDIiLCJpYXQiOjE1OTAwNzYzMDJ9._96DyV4sIDEJVAOLMHGZHy-3ikjRzr0tv26N5Iio1Xk

{
    "content": "note",
    "important": false
}

####
# get notes

# curl -i -H "Content-Type: application/json" localhost:3000/api/notes
GET http://localhost:3000/api/notes
Content-Type: application/json

####
# get note

# curl -i -H "Content-Type: application/json" localhost:3000/api/notes/5c41c90e84d891c15dfa3431
GET http://localhost:3000/api/notes/nonexistentid
Content-Type: application/json

####
# update note

# curl -i -X PUT -H "Content-Type: application/json" -d '{"content":"updated", "important":true}' localhost:3000/api/notes/5c41c90e84d891c15dfa3431
PUT http://localhost:3000/api/notes/5ebd4836900c9f6b27dc637c
Content-Type: application/json

{
  "content": "note",
  "important": true
}

####
# get users

GET http://localhost:3000/api/users
Content-Type: application/json

####
# get user

GET http://localhost:3000/api/users/5ec544d5c67a7f45d0972d05
Content-Type: application/json

####
# create user

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "test user",
  "username": "test",
  "password": "password"
}

####
# login

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}
